//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.cni {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", ConfigurationName="cni.serv")]
    public interface serv {
        
        // CODEGEN: Generating message contract since the operation challenge_generator is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:challenge_generator", ReplyAction="urn:challenge_generatorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.cni.challenge_generatorResponse1 challenge_generator(WebApplication1.cni.challenge_generatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:challenge_generator", ReplyAction="urn:challenge_generatorResponse")]
        System.Threading.Tasks.Task<WebApplication1.cni.challenge_generatorResponse1> challenge_generatorAsync(WebApplication1.cni.challenge_generatorRequest request);
        
        // CODEGEN: Generating message contract since the operation auth is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:auth", ReplyAction="urn:authResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.cni.authResponse1 auth(WebApplication1.cni.authRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:auth", ReplyAction="urn:authResponse")]
        System.Threading.Tasks.Task<WebApplication1.cni.authResponse1> authAsync(WebApplication1.cni.authRequest request);
        
        // CODEGEN: Generating message contract since the operation get_user_data is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_user_data", ReplyAction="urn:get_user_dataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.cni.get_user_dataResponse1 get_user_data(WebApplication1.cni.get_user_dataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_user_data", ReplyAction="urn:get_user_dataResponse")]
        System.Threading.Tasks.Task<WebApplication1.cni.get_user_dataResponse1> get_user_dataAsync(WebApplication1.cni.get_user_dataRequest request);
        
        // CODEGEN: Generating message contract since the operation get_xml is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_xml", ReplyAction="urn:get_xmlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.cni.get_xmlResponse1 get_xml(WebApplication1.cni.get_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_xml", ReplyAction="urn:get_xmlResponse")]
        System.Threading.Tasks.Task<WebApplication1.cni.get_xmlResponse1> get_xmlAsync(WebApplication1.cni.get_xmlRequest request);
        
        // CODEGEN: Generating message contract since the operation responde_indisponibilidade is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:responde_indisponibilidade", ReplyAction="urn:responde_indisponibilidadeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.cni.responde_indisponibilidadeResponse1 responde_indisponibilidade(WebApplication1.cni.responde_indisponibilidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:responde_indisponibilidade", ReplyAction="urn:responde_indisponibilidadeResponse")]
        System.Threading.Tasks.Task<WebApplication1.cni.responde_indisponibilidadeResponse1> responde_indisponibilidadeAsync(WebApplication1.cni.responde_indisponibilidadeRequest request);
        
        // CODEGEN: Generating message contract since the operation pesquisa is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:pesquisa", ReplyAction="urn:pesquisaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.cni.pesquisaResponse1 pesquisa(WebApplication1.cni.pesquisaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pesquisa", ReplyAction="urn:pesquisaResponse")]
        System.Threading.Tasks.Task<WebApplication1.cni.pesquisaResponse1> pesquisaAsync(WebApplication1.cni.pesquisaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class challenge_generatorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private retornoChallenge retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public retornoChallenge retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoChallenge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private retornoChallengeInfo infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public retornoChallengeInfo info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoChallengeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string challengeField;
        
        private string faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string challenge {
            get {
                return this.challengeField;
            }
            set {
                this.challengeField = value;
                this.RaisePropertyChanged("challenge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class documentos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoField;
        
        private string mensagemField;
        
        private string[] protocolosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolos", Order=2)]
        public string[] protocolos {
            get {
                return this.protocolosField;
            }
            set {
                this.protocolosField = value;
                this.RaisePropertyChanged("protocolos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoPesquisaInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultMessageField;
        
        private documentos documentoField;
        
        private string hashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public documentos documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoPesquisa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private retornoPesquisaInfo infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public retornoPesquisaInfo info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class matriculas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoField;
        
        private string matriculaField;
        
        private string protocoloField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
                this.RaisePropertyChanged("matricula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoRespondeIndisponibilidadeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string successMessageField;
        
        private string faultMessageField;
        
        private matriculas[] matriculasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string successMessage {
            get {
                return this.successMessageField;
            }
            set {
                this.successMessageField = value;
                this.RaisePropertyChanged("successMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("matriculas", Order=2)]
        public matriculas[] matriculas {
            get {
                return this.matriculasField;
            }
            set {
                this.matriculasField = value;
                this.RaisePropertyChanged("matriculas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoRespondeIndisponibilidade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private retornoRespondeIndisponibilidadeInfo infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public retornoRespondeIndisponibilidadeInfo info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoXMLInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xml_contentField;
        
        private string faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string xml_content {
            get {
                return this.xml_contentField;
            }
            set {
                this.xml_contentField = value;
                this.RaisePropertyChanged("xml_content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoXML : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private retornoXMLInfo infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public retornoXMLInfo info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class get_xml_parans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string data_inicialField;
        
        private string data_finalField;
        
        private string visualizadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string data_inicial {
            get {
                return this.data_inicialField;
            }
            set {
                this.data_inicialField = value;
                this.RaisePropertyChanged("data_inicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string data_final {
            get {
                return this.data_finalField;
            }
            set {
                this.data_finalField = value;
                this.RaisePropertyChanged("data_final");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string visualizado {
            get {
                return this.visualizadoField;
            }
            set {
                this.visualizadoField = value;
                this.RaisePropertyChanged("visualizado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class tipoUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_usuario_tipoField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string id_usuario_tipo {
            get {
                return this.id_usuario_tipoField;
            }
            set {
                this.id_usuario_tipoField = value;
                this.RaisePropertyChanged("id_usuario_tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class userData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_usuarioField;
        
        private string data_cadastroField;
        
        private string rgField;
        
        private string cpfField;
        
        private string nomeField;
        
        private string emailField;
        
        private string cargoField;
        
        private string ultimo_acessoField;
        
        private tipoUsuario tipo_usuarioField;
        
        private instituicao instituicaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string data_cadastro {
            get {
                return this.data_cadastroField;
            }
            set {
                this.data_cadastroField = value;
                this.RaisePropertyChanged("data_cadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
                this.RaisePropertyChanged("rg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
                this.RaisePropertyChanged("cpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ultimo_acesso {
            get {
                return this.ultimo_acessoField;
            }
            set {
                this.ultimo_acessoField = value;
                this.RaisePropertyChanged("ultimo_acesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public tipoUsuario tipo_usuario {
            get {
                return this.tipo_usuarioField;
            }
            set {
                this.tipo_usuarioField = value;
                this.RaisePropertyChanged("tipo_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public instituicao instituicao {
            get {
                return this.instituicaoField;
            }
            set {
                this.instituicaoField = value;
                this.RaisePropertyChanged("instituicao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class instituicao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_instituicaoField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string id_instituicao {
            get {
                return this.id_instituicaoField;
            }
            set {
                this.id_instituicaoField = value;
                this.RaisePropertyChanged("id_instituicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoUserDataInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private userData user_dataField;
        
        private string faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public userData user_data {
            get {
                return this.user_dataField;
            }
            set {
                this.user_dataField = value;
                this.RaisePropertyChanged("user_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoUserData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private retornoUserDataInfo infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public retornoUserDataInfo info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoConnectInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string session_idField;
        
        private string faultMessageField;
        
        private instituicao[] instituicoesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string session_id {
            get {
                return this.session_idField;
            }
            set {
                this.session_idField = value;
                this.RaisePropertyChanged("session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instituicoes", Order=2)]
        public instituicao[] instituicoes {
            get {
                return this.instituicoesField;
            }
            set {
                this.instituicoesField = value;
                this.RaisePropertyChanged("instituicoes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class retornoConnect : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private retornoConnectInfo infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public retornoConnectInfo info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class challenge_generatorRequest {
        
        public challenge_generatorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class challenge_generatorResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.challenge_generatorResponse challenge_generatorResponse;
        
        public challenge_generatorResponse1() {
        }
        
        public challenge_generatorResponse1(WebApplication1.cni.challenge_generatorResponse challenge_generatorResponse) {
            this.challenge_generatorResponse = challenge_generatorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class auth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string challengeField;
        
        private string signatureField;
        
        private string certificateField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string challenge {
            get {
                return this.challengeField;
            }
            set {
                this.challengeField = value;
                this.RaisePropertyChanged("challenge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
                this.RaisePropertyChanged("certificate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class authResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private retornoConnect retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public retornoConnect retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.auth auth;
        
        public authRequest() {
        }
        
        public authRequest(WebApplication1.cni.auth auth) {
            this.auth = auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.authResponse authResponse;
        
        public authResponse1() {
        }
        
        public authResponse1(WebApplication1.cni.authResponse authResponse) {
            this.authResponse = authResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class get_user_data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string session_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string session_id {
            get {
                return this.session_idField;
            }
            set {
                this.session_idField = value;
                this.RaisePropertyChanged("session_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class get_user_dataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private retornoUserData retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public retornoUserData retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_user_dataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.get_user_data get_user_data;
        
        public get_user_dataRequest() {
        }
        
        public get_user_dataRequest(WebApplication1.cni.get_user_data get_user_data) {
            this.get_user_data = get_user_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_user_dataResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.get_user_dataResponse get_user_dataResponse;
        
        public get_user_dataResponse1() {
        }
        
        public get_user_dataResponse1(WebApplication1.cni.get_user_dataResponse get_user_dataResponse) {
            this.get_user_dataResponse = get_user_dataResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class get_xml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string session_idField;
        
        private get_xml_parans paransField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string session_id {
            get {
                return this.session_idField;
            }
            set {
                this.session_idField = value;
                this.RaisePropertyChanged("session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public get_xml_parans parans {
            get {
                return this.paransField;
            }
            set {
                this.paransField = value;
                this.RaisePropertyChanged("parans");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class get_xmlResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private retornoXML retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public retornoXML retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.get_xml get_xml;
        
        public get_xmlRequest() {
        }
        
        public get_xmlRequest(WebApplication1.cni.get_xml get_xml) {
            this.get_xml = get_xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_xmlResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.get_xmlResponse get_xmlResponse;
        
        public get_xmlResponse1() {
        }
        
        public get_xmlResponse1(WebApplication1.cni.get_xmlResponse get_xmlResponse) {
            this.get_xmlResponse = get_xmlResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class responde_indisponibilidade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string session_idField;
        
        private string xml_contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string session_id {
            get {
                return this.session_idField;
            }
            set {
                this.session_idField = value;
                this.RaisePropertyChanged("session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string xml_content {
            get {
                return this.xml_contentField;
            }
            set {
                this.xml_contentField = value;
                this.RaisePropertyChanged("xml_content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class responde_indisponibilidadeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private retornoRespondeIndisponibilidade retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public retornoRespondeIndisponibilidade retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class responde_indisponibilidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.responde_indisponibilidade responde_indisponibilidade;
        
        public responde_indisponibilidadeRequest() {
        }
        
        public responde_indisponibilidadeRequest(WebApplication1.cni.responde_indisponibilidade responde_indisponibilidade) {
            this.responde_indisponibilidade = responde_indisponibilidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class responde_indisponibilidadeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.responde_indisponibilidadeResponse responde_indisponibilidadeResponse;
        
        public responde_indisponibilidadeResponse1() {
        }
        
        public responde_indisponibilidadeResponse1(WebApplication1.cni.responde_indisponibilidadeResponse responde_indisponibilidadeResponse) {
            this.responde_indisponibilidadeResponse = responde_indisponibilidadeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class pesquisa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string session_idField;
        
        private string documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string session_id {
            get {
                return this.session_idField;
            }
            set {
                this.session_idField = value;
                this.RaisePropertyChanged("session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.indisponibilidade.org.br/wsdl/")]
    public partial class pesquisaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private retornoPesquisa retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public retornoPesquisa retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pesquisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.pesquisa pesquisa;
        
        public pesquisaRequest() {
        }
        
        public pesquisaRequest(WebApplication1.cni.pesquisa pesquisa) {
            this.pesquisa = pesquisa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pesquisaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.indisponibilidade.org.br/wsdl/", Order=0)]
        public WebApplication1.cni.pesquisaResponse pesquisaResponse;
        
        public pesquisaResponse1() {
        }
        
        public pesquisaResponse1(WebApplication1.cni.pesquisaResponse pesquisaResponse) {
            this.pesquisaResponse = pesquisaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servChannel : WebApplication1.cni.serv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servClient : System.ServiceModel.ClientBase<WebApplication1.cni.serv>, WebApplication1.cni.serv {
        
        public servClient() {
        }
        
        public servClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.cni.challenge_generatorResponse1 WebApplication1.cni.serv.challenge_generator(WebApplication1.cni.challenge_generatorRequest request) {
            return base.Channel.challenge_generator(request);
        }
        
        public WebApplication1.cni.challenge_generatorResponse challenge_generator() {
            WebApplication1.cni.challenge_generatorRequest inValue = new WebApplication1.cni.challenge_generatorRequest();
            WebApplication1.cni.challenge_generatorResponse1 retVal = ((WebApplication1.cni.serv)(this)).challenge_generator(inValue);
            return retVal.challenge_generatorResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.cni.challenge_generatorResponse1> WebApplication1.cni.serv.challenge_generatorAsync(WebApplication1.cni.challenge_generatorRequest request) {
            return base.Channel.challenge_generatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.cni.challenge_generatorResponse1> challenge_generatorAsync() {
            WebApplication1.cni.challenge_generatorRequest inValue = new WebApplication1.cni.challenge_generatorRequest();
            return ((WebApplication1.cni.serv)(this)).challenge_generatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.cni.authResponse1 WebApplication1.cni.serv.auth(WebApplication1.cni.authRequest request) {
            return base.Channel.auth(request);
        }
        
        public WebApplication1.cni.authResponse auth(WebApplication1.cni.auth auth1) {
            WebApplication1.cni.authRequest inValue = new WebApplication1.cni.authRequest();
            inValue.auth = auth1;
            WebApplication1.cni.authResponse1 retVal = ((WebApplication1.cni.serv)(this)).auth(inValue);
            return retVal.authResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.cni.authResponse1> WebApplication1.cni.serv.authAsync(WebApplication1.cni.authRequest request) {
            return base.Channel.authAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.cni.authResponse1> authAsync(WebApplication1.cni.auth auth) {
            WebApplication1.cni.authRequest inValue = new WebApplication1.cni.authRequest();
            inValue.auth = auth;
            return ((WebApplication1.cni.serv)(this)).authAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.cni.get_user_dataResponse1 WebApplication1.cni.serv.get_user_data(WebApplication1.cni.get_user_dataRequest request) {
            return base.Channel.get_user_data(request);
        }
        
        public WebApplication1.cni.get_user_dataResponse get_user_data(WebApplication1.cni.get_user_data get_user_data1) {
            WebApplication1.cni.get_user_dataRequest inValue = new WebApplication1.cni.get_user_dataRequest();
            inValue.get_user_data = get_user_data1;
            WebApplication1.cni.get_user_dataResponse1 retVal = ((WebApplication1.cni.serv)(this)).get_user_data(inValue);
            return retVal.get_user_dataResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.cni.get_user_dataResponse1> WebApplication1.cni.serv.get_user_dataAsync(WebApplication1.cni.get_user_dataRequest request) {
            return base.Channel.get_user_dataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.cni.get_user_dataResponse1> get_user_dataAsync(WebApplication1.cni.get_user_data get_user_data) {
            WebApplication1.cni.get_user_dataRequest inValue = new WebApplication1.cni.get_user_dataRequest();
            inValue.get_user_data = get_user_data;
            return ((WebApplication1.cni.serv)(this)).get_user_dataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.cni.get_xmlResponse1 WebApplication1.cni.serv.get_xml(WebApplication1.cni.get_xmlRequest request) {
            return base.Channel.get_xml(request);
        }
        
        public WebApplication1.cni.get_xmlResponse get_xml(WebApplication1.cni.get_xml get_xml1) {
            WebApplication1.cni.get_xmlRequest inValue = new WebApplication1.cni.get_xmlRequest();
            inValue.get_xml = get_xml1;
            WebApplication1.cni.get_xmlResponse1 retVal = ((WebApplication1.cni.serv)(this)).get_xml(inValue);
            return retVal.get_xmlResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.cni.get_xmlResponse1> WebApplication1.cni.serv.get_xmlAsync(WebApplication1.cni.get_xmlRequest request) {
            return base.Channel.get_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.cni.get_xmlResponse1> get_xmlAsync(WebApplication1.cni.get_xml get_xml) {
            WebApplication1.cni.get_xmlRequest inValue = new WebApplication1.cni.get_xmlRequest();
            inValue.get_xml = get_xml;
            return ((WebApplication1.cni.serv)(this)).get_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.cni.responde_indisponibilidadeResponse1 WebApplication1.cni.serv.responde_indisponibilidade(WebApplication1.cni.responde_indisponibilidadeRequest request) {
            return base.Channel.responde_indisponibilidade(request);
        }
        
        public WebApplication1.cni.responde_indisponibilidadeResponse responde_indisponibilidade(WebApplication1.cni.responde_indisponibilidade responde_indisponibilidade1) {
            WebApplication1.cni.responde_indisponibilidadeRequest inValue = new WebApplication1.cni.responde_indisponibilidadeRequest();
            inValue.responde_indisponibilidade = responde_indisponibilidade1;
            WebApplication1.cni.responde_indisponibilidadeResponse1 retVal = ((WebApplication1.cni.serv)(this)).responde_indisponibilidade(inValue);
            return retVal.responde_indisponibilidadeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.cni.responde_indisponibilidadeResponse1> WebApplication1.cni.serv.responde_indisponibilidadeAsync(WebApplication1.cni.responde_indisponibilidadeRequest request) {
            return base.Channel.responde_indisponibilidadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.cni.responde_indisponibilidadeResponse1> responde_indisponibilidadeAsync(WebApplication1.cni.responde_indisponibilidade responde_indisponibilidade) {
            WebApplication1.cni.responde_indisponibilidadeRequest inValue = new WebApplication1.cni.responde_indisponibilidadeRequest();
            inValue.responde_indisponibilidade = responde_indisponibilidade;
            return ((WebApplication1.cni.serv)(this)).responde_indisponibilidadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.cni.pesquisaResponse1 WebApplication1.cni.serv.pesquisa(WebApplication1.cni.pesquisaRequest request) {
            return base.Channel.pesquisa(request);
        }
        
        public WebApplication1.cni.pesquisaResponse pesquisa(WebApplication1.cni.pesquisa pesquisa1) {
            WebApplication1.cni.pesquisaRequest inValue = new WebApplication1.cni.pesquisaRequest();
            inValue.pesquisa = pesquisa1;
            WebApplication1.cni.pesquisaResponse1 retVal = ((WebApplication1.cni.serv)(this)).pesquisa(inValue);
            return retVal.pesquisaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.cni.pesquisaResponse1> WebApplication1.cni.serv.pesquisaAsync(WebApplication1.cni.pesquisaRequest request) {
            return base.Channel.pesquisaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.cni.pesquisaResponse1> pesquisaAsync(WebApplication1.cni.pesquisa pesquisa) {
            WebApplication1.cni.pesquisaRequest inValue = new WebApplication1.cni.pesquisaRequest();
            inValue.pesquisa = pesquisa;
            return ((WebApplication1.cni.serv)(this)).pesquisaAsync(inValue);
        }
    }
}
